/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
"use strict";

systemDictionary = {
	DEBUGGING_VERBOSE: {
		en: "Enable verbose logging",
		de: "Aktivieren Sie die ausführliche Protokollierung",
		ru: "Включить подробное ведение журнала",
		pt: "Ativar registro detalhado",
		nl: "Schakel uitgebreide logboekregistratie in",
		fr: "Activer la journalisation détaillée",
		it: "Abilita la registrazione dettagliata",
		es: "Habilitar el registro detallado",
		pl: "Włącz szczegółowe rejestrowanie",
		"zh-cn": "启用详细日志记录",
	},
	LIFE360_COUNTRYCODE: {
		en: "Life360 country code for mobile phone:",
		de: "Life360-Ländercode für Mobiltelefon:",
		ru: "Код страны Life360 для мобильного телефона:",
		pt: "Código Life360 para celular:",
		nl: "Life360-landcode voor mobiele telefoon:",
		fr: "Code de pays Life360 pour téléphone portable:",
		it: "Codice paese Life360 per telefono cellulare:",
		es: "Código de país de Life360 para teléfono móvil:",
		pl: "Kod kraju Life360 na telefon komórkowy:",
		"zh-cn": "Life360手机国家区号：",
	},
	LIFE360_PASSWORD: {
		en: "Life360 password:",
		de: "Life360-Passwort:",
		ru: "Пароль Life360:",
		pt: "Senha do Life360:",
		nl: "Life360-wachtwoord:",
		fr: "Mot de passe Life360:",
		it: "Password Life360:",
		es: "Contraseña de Life360:",
		pl: "Hasło Life360:",
		"zh-cn": "Life360密码：",
	},
	LIFE360_PHONE: {
		en: "Life360 mobile phone number:",
		de: "Life360 Handynummer:",
		ru: "Номер мобильного телефона Life360:",
		pt: "Número do celular Life360:",
		nl: "Life360 mobiel telefoonnummer:",
		fr: "Numéro de téléphone mobile Life360:",
		it: "Numero di cellulare Life360:",
		es: "Número de teléfono móvil Life360:",
		pl: "Numer telefonu komórkowego Life360:",
		"zh-cn": "Life360手机号码：",
	},
	LIFE360_POLLING_INTERVAL: {
		en: "Polling interval (seconds) to retrieve Life360 data:",
		de: "Abfrageintervall (Sekunden) zum Abrufen von Life360-Daten:",
		ru: "Интервал опроса (в секундах) для получения данных Life360:",
		pt: "Intervalo de pesquisa (segundos) para recuperar dados do Life360:",
		nl: "Polling-interval (seconden) om Life360-gegevens op te halen:",
		fr: "Intervalle d'interrogation (en secondes) pour récupérer les données Life360:",
		it: "Intervallo di polling (secondi) per recuperare i dati Life360:",
		es: "Intervalo de sondeo (segundos) para recuperar datos de Life360:",
		pl: "Interwał odpytywania (sekundy) w celu pobrania danych Life360:",
		"zh-cn": "轮询间隔（秒）以检索Life360数据：",
	},
	LIFE360_USERNAME: {
		en: "Life360 email address:",
		de: "Life360 E-Mail-Adresse:",
		ru: "Адрес электронной почты Life360:",
		pt: "Endereço de e-mail Life360:",
		nl: "Life360 e-mailadres:",
		fr: "Adresse électronique Life360:",
		it: "Indirizzo email Life360:",
		es: "Dirección de correo electrónico de Life360:",
		pl: "Adres e-mail Life360:",
		"zh-cn": "Life360电子邮件地址：",
	},
	LOCATION_OBJECT_TYPE: {
		en: "Type of the geo-location-object.",
		de: "Typ des Geo-Location-Objekts.",
		ru: "Тип гео-местоположения-объекта.",
		pt: "Tipo do objeto de localização geográfica.",
		nl: "Type van het geo-locatie-object.",
		fr: "Type de l'objet géolocalisation.",
		it: "Tipo di geo-location-object.",
		es: "Tipo de geo-location-object.",
		pl: "Typ obiektu geolokalizacyjnego.",
		"zh-cn": "地理位置对象的类型。",
	},
	LatCommaLng: {
		en: "Latitude,Longitude (COMMA seperated string)",
		de: "Breite, Länge (COMMA getrennte Zeichenfolge)",
		ru: "Широта, Долгота (строка, разделенная запятыми)",
		pt: "Latitude, Longitude (string separada por Vírgula)",
		nl: "Breedtegraad, Lengtegraad (door COMMA gescheiden tekenreeks)",
		fr: "Latitude, Longitude (chaîne séparée COMMA)",
		it: "Latitudine, Longitudine (stringa separata da virgole)",
		es: "Latitud, longitud (cadena separada por COMMA)",
		pl: "Szerokość, długość geograficzna (ciąg oddzielny COMMA)",
		"zh-cn": "纬度，经度（逗号分隔的字符串）",
	},
	LatLng: {
		en: "LatLng object",
		de: "LatLng-Objekt",
		ru: "LatLng объект",
		pt: "Objeto LatLng",
		nl: "LatLng-object",
		fr: "Objet LatLng",
		it: "Oggetto LatLng",
		es: "Objeto LatLng",
		pl: "Obiekt LatLng",
		"zh-cn": "LatLng对象",
	},
	LatLon: {
		en: "LatLon object",
		de: "LatLon-Objekt",
		ru: "Объект LatLon",
		pt: "Objeto LatLon",
		nl: "LatLon-object",
		fr: "Objet LatLon",
		it: "Oggetto LatLon",
		es: "Objeto LatLon",
		pl: "Obiekt LatLon",
		"zh-cn": "LatLon对象",
	},
	LatSemicolonLng: {
		en: "Latitude;Longitude (SEMICOLON seperated string)",
		de: "Breite; Länge (SEMICOLON getrennte Zeichenfolge)",
		ru: "Широта; Долгота (разделенная строка SEMICOLON)",
		pt: "Latitude; Longitude (string separada SEMICOLON)",
		nl: "Breedtegraad; Lengtegraad (SEMICOLON gescheiden tekenreeks)",
		fr: "Latitude; Longitude (chaîne séparée SEMICOLON)",
		it: "Latitudine; Longitudine (stringa separata SEMICOLON)",
		es: "Latitud; Longitud (cadena separada SEMICOLON)",
		pl: "Szerokość; długość geograficzna (oddzielny ciąg SEMICOLON)",
		"zh-cn": "纬度；经度（SEMICOLON分隔字符串）",
	},
	LatitudeLongitude: {
		en: "LatitudeLongitude object",
		de: "LatitudeLongitude-Objekt",
		ru: "Объект LatitudeLongitude",
		pt: "Objeto LatitudeLongitude",
		nl: "LatitudeLongitude-object",
		fr: "Objet LatitudeLongitude",
		it: "Oggetto LatitudeLongitude",
		es: "Objeto LatitudeLongitude",
		pl: "Obiekt LatitudeLongitude",
		"zh-cn": "LatitudeLongitude对象",
	},
	"Life360 data": {
		en: "Life360 data",
		de: "Life360-Daten",
		ru: "Данные Life360",
		pt: "Dados Life360",
		nl: "Life360-gegevens",
		fr: "Données Life360",
		it: "Dati Life360",
		es: "Datos de Life360",
		pl: "Dane Life360",
		"zh-cn": "Life360数据",
	},
	"Location-tracking": {
		en: "Location-tracking",
		de: "Standortverfolgung",
		ru: "Расположение слежения",
		pt: "Rastreamento de local",
		nl: "Locatie tracking",
		fr: "Suivi de localisation",
		it: "Location-tracking",
		es: "Seguimiento de la ubicación",
		pl: "Śledzenie lokalizacji",
		"zh-cn": "位置追踪",
	},
	LonLatTuple: {
		en: "LonLat tuple",
		de: "LonLat-Tupel",
		ru: "Кортеж LonLat",
		pt: "Tupla LonLat",
		nl: "LonLat tuple",
		fr: "Tuple long",
		it: "Tupla solitaria",
		es: "Tupla de LonLat",
		pl: "Krotka LonLat",
		"zh-cn": "LonLat元组",
	},
	PLACE_CIRCLE: {
		en: "Circle (optional)",
		de: "Kreis (optional)",
		ru: "Круг (необязательно)",
		pt: "Círculo (opcional)",
		nl: "Cirkel (optioneel)",
		fr: "Cercle (optionnel)",
		it: "Cerchio (opzionale)",
		es: "Círculo (opcional)",
		pl: "Koło (opcjonalnie)",
		"zh-cn": "圆（可选）",
	},
	PLACE_LATITUDE: {
		en: "Latitude",
		de: "Breitengrad",
		ru: "широта",
		pt: "Latitude",
		nl: "Breedtegraad",
		fr: "Latitude",
		it: "Latitudine",
		es: "Latitud",
		pl: "Szerokość",
		"zh-cn": "纬度",
	},
	PLACE_LONGITUDE: {
		en: "Longitude",
		de: "Längengrad",
		ru: "Долгота",
		pt: "Longitude",
		nl: "Lengtegraad",
		fr: "Longitude",
		it: "Longitudine",
		es: "Longitud",
		pl: "Długość geograficzna",
		"zh-cn": "经度",
	},
	PLACE_NAME: {
		en: "Name",
		de: "Name",
		ru: "имя",
		pt: "Nome",
		nl: "Naam",
		fr: "Nom",
		it: "Nome",
		es: "Nombre",
		pl: "Imię",
		"zh-cn": "名称",
	},
	PLACE_RADIUS: {
		en: "Radius",
		de: "Radius",
		ru: "Радиус",
		pt: "Raio",
		nl: "Straal",
		fr: "Rayon",
		it: "Raggio",
		es: "Radio",
		pl: "Promień",
		"zh-cn": "半径",
	},
	PROCESS_LIFE360_CIRCLES: {
		en: "Process Life360 circles.",
		de: "Life360-Kreise verarbeiten.",
		ru: "Процесс Life360 кругов.",
		pt: "Processo Life360 círculos.",
		nl: "Process Life360 cirkels.",
		fr: "Processus Life360 cercles.",
		it: "Cerchi Process360.",
		es: "Proceso Life360 círculos.",
		pl: "Przetwarzaj Life360 kół.",
		"zh-cn": "处理Life360圈子。",
	},
	PROCESS_LIFE360_PEOPLE: {
		en: "Process Life360 people.",
		de: "Life360 Menschen verarbeiten.",
		ru: "Процесс Life360 человек.",
		pt: "Processo Life360 pessoas.",
		nl: "Process Life360 mensen.",
		fr: "Processus Life360 personnes",
		it: "Process Life360 persone",
		es: "Proceso Life360 personas",
		pl: "Przetwarzaj Life360 ​​osób.",
		"zh-cn": "处理Life360人",
	},
	PROCESS_LIFE360_PLACES: {
		en: "Process Life360 places.",
		de: "Life360 Places verarbeiten.",
		ru: "Процесс Life360 мест.",
		pt: "Processo Life360 lugares.",
		nl: "Process Life360 plaatsen.",
		fr: "Processus Life360 places",
		it: "Vita di processo 360 posti",
		es: "Proceso Life360 lugares",
		pl: "Przetwarzaj Life360 miejsc.",
		"zh-cn": "处理Life360个地方",
	},
	"Places-adapter": {
		en: "Send location data to Places-adapter.",
		de: "Places-Adapter",
		ru: "Места-адаптер",
		pt: "Adaptador de locais",
		nl: "Places-adapter",
		fr: "Places-adaptateur",
		it: "Places-adattatore",
		es: "Adaptador de lugares",
		pl: "Adapter miejsc",
		"zh-cn": "位置适配器",
	},
	SENDTO_PLACES_ADAPTER: {
		de: "Senden Sie Geo-Positionsdaten von Personen an den Places-Adapter.",
		ru: "Отправляйте данные о географическом положении людей в Places-adapter.",
		pt: "Envie dados de posicionamento geográfico de pessoas para o adaptador do Google Places.",
		nl: "Stuur gegevens voor geografische positionering van mensen naar Places-adapter.",
		fr: "Envoyez des données de géolocalisation aux personnes vers l'adaptateur Places.",
		it: "Invia i dati di geolocalizzazione delle persone a Places-adapter.",
		es: "Enviar datos de posicionamiento geográfico de personas al adaptador de lugares.",
		pl: "Wyślij dane osób o położeniu geograficznym do adaptera miejsc.",
		"zh-cn": "将人员的地理位置数据发送到地方适配器。",
	},
	SENDTO_PLACES_ADAPTER_INSTANCE: {
		en: "Places-adapter-instance to receive geo-positioning data:",
		de: "Places-Adapter-Instanz:",
		ru: "Места-адаптер экземпляр:",
		pt: "Instância do adaptador de locais:",
		nl: "Places-adapter-instantie:",
		fr: "Places-adapter-instance:",
		it: "Places-Adattatore-esempio:",
		es: "Instancia de adaptador de lugares:",
		pl: "Miejsca-adaptera-instancji:",
		"zh-cn": "Places-adapter-instance：",
	},
	SENDTO_PLACES_ADAPTER_INSTANCE_NONE: {
		en: "None",
		de: "Keiner",
		ru: "Никто",
		pt: "Nenhum",
		nl: "Geen",
		fr: "Aucun",
		it: "Nessuna",
		es: "Ninguna",
		pl: "Żaden",
		"zh-cn": "没有",
	},
	SENDTO_PLACES_ADAPTER_REGEXP: {
		en: "Regular expression pattern to filter data send to the Places-adapter.",
		de: "Muster für reguläre Ausdrücke zum Filtern von Daten, die an den Places-Adapter gesendet werden.",
		ru: "Шаблон регулярного выражения для фильтрации данных, отправляемых на Places-адаптер.",
		pt: "Padrão de expressão regular para filtrar os dados enviados para o adaptador Places.",
		nl: "Regelmatig expressiepatroon om gegevens te filteren die naar de Places-adapter worden verzonden.",
		fr: "Modèle d'expression régulière permettant de filtrer les données envoyées à l'adaptateur Places.",
		it: "Schema di espressioni regolari per filtrare i dati inviati all'adattatore Places.",
		es: "Patrón de expresión regular para filtrar los datos enviados al adaptador de lugares.",
		pl: "Wzorzec wyrażeń regularnych do filtrowania danych wysyłanych do adaptera miejsc.",
		"zh-cn": "正则表达式模式，用于过滤发送到Places-adapter的数据。",
	},
	TAB_ADVANCED: {
		en: "Advanced",
		de: "Fortgeschrittene",
		ru: "Продвинутый",
		pt: "Avançado",
		nl: "Geavanceerd",
		fr: "Avancée",
		it: "Avanzate",
		es: "Avanzado",
		pl: "zaawansowane",
		"zh-cn": "高级",
	},
	TAB_GENERAL: {
		en: "Life360",
		de: "Life360",
		ru: "Life360",
		pt: "Life360",
		nl: "Life360",
		fr: "Life360",
		it: "Life360",
		es: "Life360",
		pl: "Life360",
		"zh-cn": "生活360",
	},
	TAB_INTEGRATION: {
		en: "Integration",
		de: "Integration",
		ru: "интеграция",
		pt: "Integração",
		nl: "integratie",
		fr: "L'intégration",
		it: "Integrazione",
		es: "Integración",
		pl: "Integracja",
		"zh-cn": "积分",
	},
	TAB_MYPLACES: {
		en: "My places",
		de: "Meine Orte",
		ru: "Мои места",
		pt: "Meus lugares",
		nl: "Mijn plaatsen",
		fr: "Mes places",
		it: "I miei posti",
		es: "Mis lugares",
		pl: "Moje miejsca",
		"zh-cn": "我的地方",
	},
	TRACK_LOCATION_PEOPLE: {
		en: "Location-tracking for people.",
		de: "Verfolgen von Geopositionierungsdaten für Personen.",
		ru: "Отслеживайте данные о географическом положении людей.",
		pt: "Rastrear dados de posicionamento geográfico para pessoas.",
		nl: "Volg geografische positioneringsgegevens voor mensen.",
		fr: "Suivre les données de géolocalisation pour les personnes.",
		it: "Tieni traccia dei dati di geolocalizzazione per le persone.",
		es: "Rastree datos de geo-posicionamiento para personas.",
		pl: "Śledź dane geograficzne dla ludzi.",
		"zh-cn": "跟踪人员的地理位置数据。",
	},
	"life360 adapter settings": {
		en: "Adapter settings for Life360",
		de: "Adaptereinstellungen für life360",
		ru: "Настройки адаптера для life360",
		pt: "Configurações do adaptador para life360",
		nl: "Adapterinstellingen voor life360",
		fr: "Paramètres d'adaptateur pour life360",
		it: "Impostazioni dell'adattatore per life360",
		es: "Ajustes del adaptador para life360",
		pl: "Ustawienia adaptera dla life360",
		"zh-cn": "life360的适配器设置",
	},
	option1: {
		en: "option1",
		de: "Option 1",
		ru: "Опция 1",
		pt: "Opção 1",
		nl: "Optie 1",
		fr: "Option 1",
		it: "opzione 1",
		es: "Opción 1",
		pl: "opcja 1",
		uk: "варіант1",
		"zh-cn": "选项1",
	},
	option2: {
		en: "option2",
		de: "Option 2",
		ru: "вариант 2",
		pt: "opção 2",
		nl: "Optie 2",
		fr: "Option 2",
		it: "opzione 2",
		es: "opcion 2",
		pl: "Opcja 2",
		uk: "варіант2",
		"zh-cn": "选项2",
	},
};
